# Generated by Django 5.2.3 on 2025-06-19 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0004_alter_subtask_deadline_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_title_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 22, 4, 3, 16423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 22, 4, 3, 16423, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title', 'created_at'), name='unique_task_title_date'),
        ),
    ]
