# Generated by Django 5.2.3 on 2025-06-22 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0005_remove_task_unique_task_title_date_remove_task_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 15, 4, 41, 600910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 15, 4, 41, 600910, tzinfo=datetime.timezone.utc)),
        ),
    ]
