# Generated by Django 5.2.3 on 2025-06-23 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0021_alter_subtask_deadline_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 18, 39, 23, 967158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 18, 39, 23, 967158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title', 'description'], name='task_manage_title_a2c850_idx'),
        ),
    ]
