# Generated by Django 5.2.3 on 2025-06-23 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0022_alter_subtask_deadline_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_manage_title_a2c850_idx',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 18, 39, 50, 517526, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 18, 39, 50, 517526, tzinfo=datetime.timezone.utc)),
        ),
    ]
