# Generated by Django 5.2.3 on 2025-06-23 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0023_remove_task_task_manage_title_a2c850_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 18, 43, 7, 584221, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 18, 43, 7, 584221, tzinfo=datetime.timezone.utc)),
        ),
    ]
