# Generated by Django 5.2.3 on 2025-07-14 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskManager", "0033_alter_subtask_deadline_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 15, 11, 22, 49, 603423, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 15, 11, 22, 49, 603423, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
