# Generated by Django 5.2.3 on 2025-07-17 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskManager", "0036_alter_subtask_deadline_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 18, 7, 39, 6, 385992, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 18, 7, 39, 6, 385992, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
