# Generated by Django 5.2.3 on 2025-06-19 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('profile', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль')),
                ('deleted', models.BooleanField(default=False, help_text='Если False - автор активен. Если True - автора \\ больше нет в списке доступных', verbose_name='Удалён ли автор')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг автора')),
            ],
        ),
    ]
