# Generated by Django 5.2.3 on 2025-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(choices=[('py', 'Python'), ('c#', 'C#'), ('java', 'Java')])),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')])),
                ('project', models.ManyToManyField(related_name='developers', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('back', 'Backend'), ('front', 'Frontend'), ('qa', 'Q&A'), ('ui', 'Design'), ('devops', 'DevOPS')], max_length=255)),
                ('project', models.ManyToManyField(related_name='tags', to='project.project')),
            ],
        ),
    ]
