# Generated by Django 5.2.3 on 2025-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(choices=[('java', 'Java'), ('py', 'Python'), ('c#', 'C#')]),
        ),
    ]
