# Generated by Django 5.2.3 on 2025-06-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_title_project_name_alter_project_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='developers', to='project.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(choices=[('c#', 'C#'), ('py', 'Python'), ('java', 'Java')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='project.project'),
        ),
    ]
