# Generated by Django 5.2.3 on 2025-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_developer_project_alter_project_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='developers', to='project.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(choices=[('c#', 'C#'), ('java', 'Java'), ('py', 'Python')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='tags', to='project.project'),
        ),
    ]
