# Generated by Django 5.2.3 on 2025-06-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_developer_project_alter_project_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(choices=[('java', 'Java'), ('c#', 'C#'), ('py', 'Python')]),
        ),
    ]
