# Generated by Django 5.2.3 on 2025-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(choices=[('java', 'Java'), ('py', 'Python'), ('c#', 'C#')]),
        ),
    ]
