# Generated by Django 5.2.3 on 2025-06-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lang',
            new_name='language',
        ),
    ]
