# Generated by Django 5.2.3 on 2025-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_lang_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('java', 'Java'), ('c#', 'C#'), ('py', 'Python')]),
        ),
    ]
