# Generated by Django 5.2.3 on 2025-06-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('c#', 'C#'), ('java', 'Java')]),
        ),
    ]
