# Generated by Django 5.2.3 on 2025-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('java', 'Java'), ('py', 'Python'), ('c#', 'C#')]),
        ),
    ]
