# Generated by Django 5.2.3 on 2025-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_alter_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('c#', 'C#'), ('java', 'Java'), ('py', 'Python')]),
        ),
    ]
