# Generated by Django 5.2.3 on 2025-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0040_alter_project_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="language",
            field=models.CharField(
                choices=[("py", "Python"), ("java", "Java"), ("c#", "C#")]
            ),
        ),
    ]
