# Generated by Django 5.2.3 on 2025-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0043_alter_project_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="language",
            field=models.CharField(
                choices=[("c#", "C#"), ("java", "Java"), ("py", "Python")]
            ),
        ),
    ]
